name: Build

on:
  push:
    branches: [ "master", "renderer-revamp" ]
  pull_request:
    branches: [ "master", "renderer-revamp" ]
  workflow_dispatch:
    

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Install .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore projects
      run: dotnet restore
      
    - name: Build
      run: dotnet build
